# Generated by Django 4.2.7 on 2025-04-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_add_interest_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='interest_category',
            field=models.CharField(blank=True, choices=[('muzik', 'Müzik'), ('spor', 'Spor'), ('sanat', 'Sanat'), ('bilim', 'Bilim ve Teknoloji'), ('egitim', 'Eğitim'), ('yemek', 'Yemek'), ('seyahat', 'Seyahat'), ('sinema', 'Sinema'), ('tiyatro', 'Tiyatro'), ('edebiyat', 'Edebiyat')], max_length=50, verbose_name='İlgi Alanı Kategorisi'),
        ),
    ]
