# Generated by Django 4.2.7 on 2025-05-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_interest_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='interest_category',
            field=models.CharField(blank=True, choices=[('muzik', 'Müzik'), ('konser', 'Konser'), ('spor', 'Spor'), ('sanat', 'Sanat'), ('bilim', 'Bilim ve Teknoloji'), ('teknoloji', 'Teknoloji'), ('egitim', 'Eğitim'), ('eglence', 'Eğlence'), ('yemek', 'Yemek'), ('seyahat', 'Seyahat'), ('sinema', 'Sinema'), ('tiyatro', 'Tiyatro'), ('edebiyat', 'Edebiyat'), ('doga', 'Doğa Aktivitesi'), ('seminer', 'Seminer')], max_length=50, verbose_name='İlgi Alanı Kategorisi'),
        ),
    ]
