# Generated by custom command
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='interests',
            field=models.CharField(blank=True, help_text='Virgülle ayrılmış ilgi alanları', max_length=255),
        ),
    ]
