# Generated by Django 4.2.7 on 2025-05-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_categories',
            field=models.CharField(blank=True, help_text='Kullanıcının favori kategorileri (sıralı, virgülle ayrılmış)', max_length=255),
        ),
    ]
